imports:
    - javascript
    - php

filter:
    excluded_paths: [3rdparty/*, js/vendor/*, js/public/app.js, tests/]
    dependency_paths:
        - vendor/christophwurst/nextcloud

# Code coverage is not collected at the moment to speed up the Scrutinizer analysis, especially on the
# private fork of the project where there is no Travis running the tests.
#tools:
#    external_code_coverage:
#        timeout: 300    # Timeout in seconds, 5 minutes
#        runs: 2         # Scrutinizer waits for the first 2 coverage submissions (unit & integration)

build:
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev "christophwurst/nextcloud ^12.0.0"
            tests:
                override:
                    - php-scrutinizer-run
